name: Generate PDF from LaTeX

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: documentation.tex
        working_directory: freephoenix888

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: generated-pdf
        path: ./freephoenix888/documentation.pdf

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ./freephoenix888/documentation.pdf
        tag_name: v${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

